# Generated by Django 5.2.11 on 2026-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                condition=models.Q(("point__gte", 0)), name="user_point_non_negative"
            ),
        ),
    ]
