# Generated by Django 5.2.11 on 2026-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_BIDDING", "On Bidding"),
                    ("CONTRACTED", "Contracted"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ON_BIDDING",
                max_length=20,
            ),
        ),
    ]
