# Generated by Django 5.2.11 on 2026-03-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name"]},
        ),
    ]
